<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!--<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>-->
    <ApplicationIcon>Assets\logo.ico</ApplicationIcon>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\logo.ico" />
    <Content Include="Shaders\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Shaders\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="Assets\Fonts\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Assets\Fonts\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Locales/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Locales\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bliss" Version="1.4.2" />
    <PackageReference Include="Hexa.NET.ImGui" Version="2.2.9" />
    <PackageReference Include="Hexa.NET.ImGuizmo" Version="2.2.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
    <PackageReference Include="TinyBCSharp" Version="0.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibLunacy\LibLunacy.csproj" />
    <ProjectReference Include="..\LibreFios\LibreFios\LibreFios.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Fonts\" />
    <Folder Include="Core\MenuBar\" />
    <Folder Include="Locales\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Locales\en.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
